name: GNUB Auto Deploy
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: React build
      working-directory: ./react-front
      run: |
        npm install
        npm run build

    - name: Spring Boot build
      working-directory: ./GNUB
      run: |
        chmod +x ./gradlew
        ./gradlew clean build -x test

    - name: Save EC2 PEM key
      run: |
        echo "${{ secrets.EC2_KEY }}" | base64 -d > gnub.pem
        chmod 600 gnub.pem

    - name: Copy files to EC2
      run: |
        scp -i gnub.pem -o StrictHostKeyChecking=no -r ./react-front/build/* ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/gnub-front/
        scp -i gnub.pem -o StrictHostKeyChecking=no ./GNUB/build/libs/GNUB-0.0.1-SNAPSHOT.jar ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/gnub-back/

    - name: Restart Spring Boot on EC2
      run: |
        ssh -i gnub.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
        pkill -f 'java -jar' || true
        nohup java -jar /home/ubuntu/gnub-back/GNUB-0.0.1-SNAPSHOT.jar > /home/ubuntu/gnub-back/app.log 2>&1 &
        EOF
